import { Action, ActionEventType, ActionCallback, ConstraintCallback } from '../actions.js';
import { MessageEventCtx, UserEventCtx, VoiceChannelsEventCtx, ThreadEventCtx, ChannelEventCtx } from '../actions.js';
import { PredefinedActionCallbacks, PredefinedActionConstraints } from '../actions.js';

export const eclairAIYesNoAction: Action<MessageEventCtx> = {
    activationEventType: ActionEventType.OnMessageCreateOrEdit,
    constraints: [
        (msg) => msg.content.toLowerCase().startsWith(`<@${msg.client.user?.id}> czy`),
    ],
    callbacks: [
        (msg) => {
            const responses = [
                'tak',
                'nie',
                'idk',
                'kto wie',
                'raczej nie',
                'niezbyt',
                'raczej tak',
                'definitynie NIE',
                'definitywnie TAK',
                'TAK!',
                'NIE!',
                'zaprzeczam',
                'potwierdzam',
                'nie chce mi sie tego osądzać',
                'być może',
                'prawdopodobnie tak',
                'prawdopodobnie nie',
                'nie mam zdania',
                'ciężko powiedzieć',
                'to tajemnica',
                'zdecydowanie tak',
                'zdecydowanie nie',
                'jak najbardziej',
                'absolutnie nie',
                'to zależy',
                'nie jestem pewien',
                'wątpię',
                'oczywiście',
                'ani trochę',
                'brzmi sensownie',
                'brzmi absurdalnie',
                'zapytaj jutro',
                'moja kula mówi NIE',
                'moja kula mówi TAK',
                'zgadnij sam',
                'to sekret',
                'a co ty myślisz?',
                'nie w tym życiu',
                'ależ oczywiście!',
                'skądże znowu',
                'bez dwóch zdań',
                'nawet o tym nie myśl',
                'tylko głupiec by się zgodził',
                '100% tak',
                '100% nie',
                'nie teraz',
                'teraz tak',
                'zależy od pogody',
                'wszystko możliwe',
                'absolutna prawda',
                'totalna bzdura',
                'zgadzam się',
                'odrzucam',
                'hehe, nie',
                'hehe, tak',
                'to pozostaje niewiadomą',
                'zapytaj jeszcze raz',
                'moja odpowiedź brzmi NIE',
                'moja odpowiedź brzmi TAK',
                'chyba żartujesz',
                'brzmi śmiesznie, ale tak',
                'brzmi groźnie, więc nie',
                'muszę się zastanowić',
                'nie mam na to siły',
                'to pytanie bez sensu',
                'sam sobie odpowiedz',
                'kto by to wiedział?',
                'niech los zadecyduje',
                'rzut monetą by pomógł',
                'nie widzę przeciwwskazań',
                'zdecydowanie odradzam',
                'czemu nie?',
                'lepiej nie',
                'nigdy w życiu',
                'nie teraz, później tak',
                'gdy gwiazdy się ułożą',
                'może kiedyś',
                'może jutro',
                'na pewno',
                'zdecydowanie nie dzisiaj',
                'ależ skąd',
                'niech Ci będzie',
                'jak sobie chcesz',
                'brzmi jak TAK',
                'brzmi jak NIE',
                'ja bym się zgodził',
                'ja bym odmówił',
                'tylko jeśli chcesz problemów',
                'tylko jeśli chcesz szczęścia',
                'to nie takie proste',
                'proste: tak',
                'proste: nie'
            ];
            const response: string = (msg.content.toLowerCase().includes('windows jest lepszy od linux') || msg.content.toLowerCase().includes('windows jest lepszy niz linux') || msg.content.toLowerCase().includes('windows jest lepszy niż linux')) ? 'NIE' : ((msg.content.toLowerCase().includes('linux jest lepszy od windows') || msg.content.toLowerCase().includes('linux jest lepszy niz windows') || msg.content.toLowerCase().includes('linux jest lepszy niż windows')) ? 'TAK' : (responses[Math.floor(Math.random() * responses.length)]));
            return msg.reply(response);
        }
    ]
};